### ISSUE TITLE
Automatically enable this extension

### ISSUE THREAD

**Issue by psychemedia** [yunier-olivera/markdown-quarto-word-count#1]
Is it possible to have a setting that will allow this extension to be enabled automatically, either within a project, or across all projects?

**Comment by yunier-olivera** [comment]
Hi! Thanks for the suggestion about auto-enabling the extension. It's a good idea.

Right now, I'm tied up with other projects, so I can't tackle this immediately. But it's on my radar for future updates. I'll keep you posted when I get to it.

**Comment by yunier-olivera** [comment]
Hi @psychemedia,

The feature you suggested was implemented. Now, the extension can be automatically enabled within a specific project or globally across all projects. This enhancement is included in the most recent release.

For detailed instructions on configuring this new feature, please take a look at the updated README.md file.

Thank you sincerely for your contribution. Please feel free to try out the new version and let me know if it works as expected or if there are any further improvements you'd like to see.

Warm regards,
@yunier-olivera
