### ISSUE TITLE
Publish to OpenVSX repository

### ISSUE THREAD

**Issue by andreatitolo** [yunier-olivera/markdown-quarto-word-count#2]
Hi! Thanks for this extension, I think it's a great addition for anyone working with quarto files.
I don't know if it is possible at all or how easy it is, so apologies in advance if it is a weird question, but would it be possible to publish the extension also on [OpenVSX](https://open-vsx.org)? This way also people using [VSCodium](https://vscodium.com/) can use it :)

Thank you in advance and have a great day!

**Comment by yunier-olivera** [comment]
Hi!
Thank you so much for your kind words, and for the suggestion about OpenVSX.
I'll look into the requirements and see how we can make it available for VSCodium users as well.
Appreciate your input!
Best!

**Comment by andreatitolo** [comment]
Thanks a lot for considering it :)

**Comment by yunier-olivera** [comment]
Hi! 

Just wanted to let you know that the extension is now available on OpenVSX for VSCodium users. Thank you for your input!

Best!

**Comment by andreatitolo** [comment]
Thanks a lot! I will start using it immediately :)
