### ISSUE TITLE
Hyphens in words confuse wordcount

### ISSUE THREAD

**Issue by IFcoltransG** [yunier-olivera/markdown-quarto-word-count#3]
Open a new file, set it to markdown, and type `two-words`. The word count says there are 2 words, treating the hyphen as a word separator. Select both words, and the word count displays "1 of 2 word", treating hyphen-separated phrases as a single word. This is inconsistent.

**Comment by yunier-olivera** [comment]
Hello IFcoltransG,

Thank you for pointing out this bug. I’ve also noticed issues with decimals and apostrophes. Thanks!

I've addressed these in the upcoming update.

Thanks for your feedback!

Best!
